config/routes.rb
Rails.application.routes.draw do
  resources :tags
  root to: "projects#index"
  get 'home' => "projects#home", :as => "home"

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
  resources :projects do
    member do
     get 'detail'
     get 'record'
    end
  end
  resources :photos
     
  post 'projects/playlist' => 'project#post_order'

end

app/models/project.rb
class Project < ActiveRecord::Base
  enum status: [:private_project, :public_project, :group_project]
  validates :project_name , presence: true
  validates :user , presence: true
  validates :status , presence: true
  validates_uniqueness_of :user, scope: :project_name
  validates :project_name, length:{maximum:30,minimum:4}
  has_many :photo
  has_many :tagging
  belongs_to :user

  def thumbnail_src
    t = Photo.where(:project => self, :order_in_project => self.thumbnail_picture_id).first
    src = t.try(:thumbnail).try(:url).to_s
    if src == ""
      src = t.try(:file).try(:url).to_s
    end

    if src == nil or src == ""
      return "/images/noimage.gif"
    else
      return convert_file_to_s3 src
    end
  end

  def date
    self.updated_at.strftime "%y/%m/%d"
  end
  # development only
  def convert_file_to_s3 url
    url.gsub(/^.*https%3A/,"https:/")
  end

  def visible_to_user? user
    self.public_project? or self.user == user
  end
end

app/controllers/project.rb
require "fabnavi_utils"
Gdworker::App.controllers :project do
  before do
  end

  post "/postConfig" do
    data = params[:data]
    puts data
    imgURLs = JSON.parse data
    proj = Project.find_project(params[:author],params[:project_id])
    pictureURLs= proj.picture
    pictureURLs.map!{ |pict|
      pict.order_in_project = -1
      pict.save
    }
    imgURLs.each_with_index do |url,i|
      unless url = imgURLs[i]["globalURL"] then next end 
      unless pict = pictureURLs.find_by(:url =>url) then
        pict = Picture.new(:url => url ,:project => proj)
      end
      pict.order_in_project = i+1

      if thumbnail = imgURLs[i]["thumbnailURL"] then
        pict.thumbnail_url = thumbnail
      end
      pict.save
    end
    "hoge"
  end

  get "/delete" do
    unless session[:authorName] == params[:author] then return end
    res = Project.find_project(params[:author],params[:project_id])
    res.try(:delete)
  end

  post "/setThumbnail" do
    unless session[:authorName] == params[:author] then return end
    index = params[:thumbnail]
    project_name = params[:project_id]
    author = params[:author]
    proj = Project.joins(:author).readonly(false).find_by(:project_name => project_name, :authors => {:name => author})
    puts proj
    proj.thumbnail_picture_id = index.to_i
    proj.save
  end 

  post "/postPicture" do
    #TODO check the header of pict
    unless session[:authorName] == params[:author] then 
      return 
    end
    data = params[:data]
    id = params[:project_id]
    url = params[:url]
    pict = Base64.decode64(data)
    fileName =File.basename(/^http.*.(?i:JPG)/.match(url)[0])
    filePath = id+'/'+fileName
    puts filePath
    save_pict_S3(filePath,pict) 
    "https://s3-ap-northeast-1.amazonaws.com/files.fabnavi/"+filePath
  end 

  post "/new" do
    @projectName = params[:ProjectName]
    @authorName = session[:authorName]
    proj = Project.joins(:author).find_by(:authors=>{name:@authorName},:project_name =>@projectName)
    if proj == nil then
      author = Author.find_by(:email => session[:email], :name => @authorName)
      p = Project.new 
      p.author = author
      p.project_name = @projectName
      p.status = 0
      p.thumbnail_picture_id = 0
      if p.save then 
        redirect_to "/add/"+@authorName+"/"+@projectName
      else 
        flash[:notice] = "Error Something."
        render "project/newProject"
      end 
    else 
      flash[:notice] = "Project name is Duplicated. Change project name"
      render "project/newProject"
    end
  end

  post "/status" do
    puts params.to_json
    if proj = Project.find_project(session[:authorName],session[:projectName]) then
      puts proj.to_json
      proj.status = 0
      proj.status = 1 if params[:status] == "Public"
      proj.project_name = params[:ProjectName] unless params[:ProjectName] == session[:projectName]
      if proj.save then
        redirect_to "/"
      else 
        redirect_to "/status/"+session[:authorName] + "/" + session[:projectName]
      end 
    end 
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy, :detail]
  before_action :set_project_with_pictures, only: [:show, :record]
  before_action :authenticate! , only: [:new, :home, :edit, :record, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order('updated_at desc').all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
   render layout: 'player'
  end

  def record
    render layout: 'player'
  end

  def detail

  end

  def home
    @projects = Project.joins(:user).order('updated_at desc').where(:user => current_user)
    render action: :index
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def post_order

  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to record_project_path(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    flash[:notice] = 'Project was successfully destroyed.' 
    render :json => @project
  end

  private

    def set_project
      @project = Project.find(params[:id])
      unless @project.visible_to_user? current_user
       flash[:alert] = "This project is private"
       redirect_to root_path
      end
    end

    def set_project_with_pictures
      @project = Project.find(params[:id])

      unless @project.visible_to_user? current_user
        flash[:alert] = "This project is private"
        redirect_to root_path
      end
        @pictures = Photo.where(:project => @project)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      taggings = params.require(:project).permit(:tagging)
      tags = taggings[:tagging].split(",").map {|t| t.gsub(/\s+/,"")}
      tags.uniq!
      puts tags
      tag_models = tags.collect{|t| Tag.find_or_create_by(name: t)}
      tagging_models = tag_models.map { |t|  Tagging.new({tag:t, project:@project} ) unless Tagging.where(tag_id: t.id, project_id: @project.id).first}
      tagging_models.compact!
      tagging_models.each { |t| t.save if t}

      saved_tagging_models = Tagging.where(project: @project)
      saved_tagging_models.each {|t| t.destroy unless tags.include? t.tag.name}

      params.require(:project).permit(:project_name, :thumbnail_picture_id,:status, :description)
    end

    def authenticate!
     unless user_signed_in?
      flash[:notice] = "You need to sign in"
      redirect_to root_path
     end
    end
end

app/helpers/project_helper.rb
# Helper methods defined here can be accessed in any controller or view in the application

Gdworker::App.helpers do
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
= form_for @project, :html => {:class => "form-box"} do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :project_name
    = f.text_field :project_name,  class: "form-text"
  .field
    = f.label "Project description"
    = f.text_area :description, rows: 10, class: "form-text"
  .field
    = f.label "Tag"
    = f.text_area :tagging, rows: 1, class: "form-text", value: @project.tagging.all.map { |t| t.tag.try(:name)}.compact.to_s.gsub(/\"|\[/,"").gsub(/\]/,",")

  -if controller.action_name == "new"  
    center 
      | You need calibration sheet and Fixfox Addon !!
      br
      | Please print this PDF and install the Addon.
    a.pdf href="https://drive.google.com/folderview?id=0B9k4M70SGKlAQ0xtTTNnOWgwOXM&usp=sharing" target="_blank"
      =image_tag image_path('pdf.png')
    a.pdf href="http://crest-multimedia-web.s3.amazonaws.com/tsuka/fabnavi-preview/public/sonycameraremotecontroller.xpi" target="_blank"
      =image_tag image_path('firefox-extension.png')
    
  .actions = f.submit

app/views/projects/_player.html.slim
#contents
  #thumbnailList
  img#photo height="3715"  width="4928"  crossorigin="anonymous"
  canvas#cvs
  #counter
  #editor
  .filter
    .message
  img#navigation-image
  .exit-alert
    img.alert-img[src="#{image_path('alert.png')}"]
  .meter
    .progress-bar
    .progress-value 0/0

app/views/projects/edit.html.slim
- content_for (:css_link) do
  = stylesheet_link_tag "project_list" 

h1.form-title Editing project

== render 'form'

= link_to 'Show', @project
'|
= link_to 'Back', projects_path

app/views/projects/index.html.slim
-content_for( :css_link ) do
  =stylesheet_link_tag 'project_list', media: 'all', 'data-turbolinks-track' => true
-content_for( :js_include ) do
  =javascript_include_tag 'project_list', media: 'all', 'data-turbolinks-track' => true
  javascript:
    function boot(){
      ProjectList.init();
    }

.projects
    - @projects.each do |project|
      .project-box.project[data="#{project.id}" raw="#{project.to_json.gsub("id","thumbnail_url\":\""+project.thumbnail_src+"\",\"id")}"]
        -puts project.thumbnail_src.to_s
        .thumbnail
          img src="#{{project.thumbnail_src}}"
          - if controller.action_name == "home"
            - if project.private_project?
              img#status-icon src="#{{image_path('private.png')}}"
            -else 
              img#status-icon src="#{{image_path('public.png')}}"
        .project-name = project.project_name
        .box
          = image_tag project.try(:user).try(:avatar).try(:url), class: 'user-icon'
          .username #{project.try(:user).try(:name)}
          .date Date:#{project.date}
        ul.actions.hide
          li.action.action-box
            =image_tag image_path("p_play.png")
            = link_to 'Play',    project_path(project) 
          li.action.action-box
            =image_tag image_path("p_record.png")
            = link_to 'Record',  record_project_path(project)
          li.action.action-box
            =image_tag image_path("p_detail.png")
            = link_to 'Detail',  detail_project_path(project)
          li.action.action-box
            =image_tag image_path("p_edit.png")
            = link_to 'Edit',    edit_project_path(project)
          li.action.action-box.delete
            =image_tag image_path("p_delete.png")
            = link_to 'Delete',  project, method: :delete, data: {confirm: "Are you sure to delete?"}

app/views/projects/new.html.slim
- content_for (:css_link) do
  = stylesheet_link_tag "project_list" 
h1.form-title Create New project

== render 'form'


= link_to 'Back', projects_path

app/views/projects/record.html.slim
-content_for( :js_include ) do
  javascript:
    function boot(){
      Fabnavi.add();
    }

javascript:
  PICTURES_DATA = #{{@pictures.to_json}}
  PROJECT_DATA = #{{@project.to_json}}
 
== render 'player'

app/views/projects/show.html.slim
-content_for( :js_include ) do
  javascript:
    function boot(){
      Fabnavi.play();
    }

javascript:
  PICTURES_DATA = #{{@pictures.to_json}}
  PROJECT_DATA = #{{@project.to_json}}

== render 'player'