config/routes.rb
Rails.application.routes.draw do
  resources :tags
  root to: "projects#index"
  get 'home' => "projects#home", :as => "home"

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
  resources :projects do
    member do
     get 'detail'
     get 'record'
    end
  end
  resources :photos
     
  post 'projects/playlist' => 'project#post_order'

end

app/controllers/admin_photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def photo_params
    params.require(:photo).permit(:file, :thumbnail, :project_id, :order_in_project)
  end

  def authenticate! 
    unless user_signed_in?
      flash[:notice] = "You need to sign in"
      redirect_to root_path
    end
  end
end

app/views/admin_photos/_form.html.slim
= form_for @photo do |f|
  - if @photo.errors.any?
    #error_explanation
      h2 = "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      ul
        - @photo.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :file
    = f.file_field :file
  .field
    = f.label :thumbnail
    = f.file_field :thumbnail
  .field
    = f.label :project_id
    = f.text_field :project_id
  .field
    = f.label :order_in_project
    = f.number_field :order_in_project
  .actions = f.submit

app/views/admin_photos/edit.html.slim
h1 Editing photo

== render 'form'

= link_to 'Show', @photo
'|
= link_to 'Back', photos_path

app/views/admin_photos/index.html.slim
h1 Listing photos

table
  thead
    tr
      th File
      th Thumbnail
      th Project
      th Order in project
      th
      th
      th

  tbody
    - @photos.each do |photo|
      tr
        td = photo.file
        td = photo.thumbnail
        td = photo.project_id
        td = photo.order_in_project
        td = link_to 'Show', photo
        td = link_to 'Edit', edit_photo_path(photo)
        td = link_to 'Destroy', photo, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Photo', new_photo_path

app/views/admin_photos/new.html.slim
h1 New photo

== render 'form'

= link_to 'Back', photos_path

app/views/admin_photos/show.html.slim
p#notice = notice

p
  strong File:
  =image_tag @photo.file
p
  strong Thumbnail:
  =image_tag @photo.thumbnail
p
  strong Project:
  = @photo.project_id
p
  strong Order in project:
  = @photo.order_in_project

= link_to 'Edit', edit_photo_path(@photo)
'|
= link_to 'Back', photos_path