config/routes.rb
Rails.application.routes.draw do
  resources :tags
  root to: "projects#index"
  get 'home' => "projects#home", :as => "home"

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
  resources :projects do
    member do
     get 'detail'
     get 'record'
    end
  end
  resources :photos
     
  post 'projects/playlist' => 'project#post_order'

end

app/controllers/admin_projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :detail]
  before_action :authenticate! , only: [:new, :home, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
   render layouts: :player
  end

  def detail

  end

  def home
    @projects = Project.all
    render action: :index
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to detail_project_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to detail_project_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      unless @project.visible_to_user? current_user
       flash[:alert] = "This project is private"
       redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :thumbnail_picture_id,:status, :description)
    end

    def authenticate!
     unless user_signed_in?
      flash[:notice] = "You need to sign in"
      redirect_to root_path
     end
    end
end

app/views/admin_projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :project_name
    = f.text_field :project_name
  .field
    = f.label :description
    = f.text_field :description
  .field 
    = f.label :status
    = f.select :status, Project.statuses.keys
  .actions = f.submit

app/views/admin_projects/detail.html.slim
p#notice = notice

p
  strong Project name:
  = @project.project_name
p
  strong Thumbnail picture:
  = @project.thumbnail_picture_id
p
  strong User:
  = @project.user.name
p
  strong Status:
  = @project.status
p
  strong Description:
  = @project.description

= link_to 'Edit', edit_project_path(@project)
'|
= link_to 'Back', projects_path

app/views/admin_projects/edit.html.slim
h1 Editing project

== render 'form'

= link_to 'Show', @project
'|
= link_to 'Back', projects_path

app/views/admin_projects/index.html.slim
-content_for( :css_link ) do
  =stylesheet_link_tag 'project_list'

h1 Listing projects

table
  thead
    tr
      th Project name
      th Thumbnail picture
      th User
      th Status
      th Description
      th
      th
      th

  tbody
    - @projects.each do |project|
      tr.project
        td.project-name = project.project_name
        td.thumbnail 
          img src="#{{project.thumbnail_src}}"
        td = project.user_id
        td = project.status
        td = project.description
        td = link_to 'Play',    project_path(project)
        td = link_to 'Record',  record_project_path(project)
        td = link_to 'Detail',  detail_project_path(project)
        td = link_to 'Edit',    edit_project_path(project)
        td = link_to 'Delete',  project, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Project', new_project_path

app/views/admin_projects/new.html.slim
h1 New project

== render 'form'

= link_to 'Back', projects_path

app/views/admin_projects/show.html.slim
h1 Play Project!